---
# tasks file for configure_master

- name: "Configuring YUM repository for kubernetes"
  yum_repository:
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
    - kubelet
    - kubeadm
    - kubectl
    description: yum repo for kubernetes

- name: "Installing kubeadm, kubelet, kubectl in Master"
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop:
  - kubeadm
  - kubelet
  - kubectl

- name: "Starting and Enabling kubelet"
  service:
    name: kubelet
    state: started
    enabled: yes

- name: "Downloading all Docker Images used by Master"
  command: kubeadm config images pull
  changed_when: false
  ignore_errors: yes

- name: "Changing Docker cgroup driver"
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: "Restarting docker"
  service:
    name: docker
    state: restarted

- name: "Installing iproute-tc in Master"
  package:
    name: iproute-tc
    state: present

- name: "Copying k8s.conf file"
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: "Restarting sysctl"
  shell: sysctl --system

- name: "Starting the Master"
  command: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"

- name: "Creating .kube directory, copying admin.conf file, changing permissions for config"
  shell: "{{ item }}"
  loop:
  - "mkdir -p $HOME/.kube"
  - "echo Y | sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
  - "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: "Configuring Flannel"
  command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
